### ISSUE TITLE
Issues with spaces in table names

### ISSUE THREAD

**Issue by samnabi** [sleiman/airtable-php#25]
I had a rough time trying to debug this issue. Trying to add a new record to one of my tables, and this was producing a blank response. No error message, but the record was not getting created:

`$airtable->saveContent('Table Name', $fields);`

I finally figured out, after much trial and error, that the space in the table name needed to be url encoded.

So this works:

`$airtable->saveContent('Table%20Name', $fields);`

But it feels very hacky.

**Comment by glaliberte** [comment]
Hi @samnabi ,

It is quite impossible that you need to do this manually since it has been fixed 1 year ago in a release.

See this line of code:
https://github.com/sleiman/airtable-php/blob/ee2b7fc14ddd4dc7f142344556806a620f169a1f/src/Airtable.php#L52 

Could you try updating airtable-php using composer?

If you are not using composer, you might want to download the latest release.

Hope this helps.
