### ISSUE TITLE
504 Gateway Timeout for large airtable

### ISSUE THREAD

**Issue by ezitsolutions** [sleiman/airtable-php#32]
I have an airtable with 2000+ records.  I'm trying to fetch all the records and insert them into mysql.  I keep getting a 504 Gateway timeout after a certain amount of time.  The records still get inserted - but is there a way to prevent that error?

**Comment by glaliberte** [comment]
Hi @ezitsolutions ,

The problem you're facing is not really related to airtable-php.

Your server is facing a timeout since it's taking more time to execute your script than your configuration allows.

You can try increasing the **Maximum Execution Time** of your PHP server.

https://stackoverflow.com/questions/16171132/how-to-increase-maximum-execution-time-in-php

**Comment by ezitsolutions** [comment]
Thanks.  That fixed the issue.
