### ISSUE TITLE
Retrieve a record by ID (faster than quickCheck)

### ISSUE THREAD

**Issue by peachp** [sleiman/airtable-php#37]
Hi there. First, thanks a lot for this wrapper. I use it in a couple of my projects.

I saw there is a quickCheck call, which would return one record if you filter right.

In my application, I also have the recIds of the Airtable records, so I wonder if there is a way to retrieve single record and if it is noticeably faster compared to quickCheck. To clarify, I mean this API URI:
`https://api.airtable.com/v0/appE5iirABCD9emg7/MyTable/reclnxjiMeSl1234`

I know that in most cases people don't use recIds, but something like the email address as their IDs, but in my case I want to make it more robust, so I ask my editors to copy&paste the recId of the record they want to show in our CMS, because Airtable is not very strict with the natural keys and allows duplicates and to change them.

**Comment by sleiman** [comment]
Hi @peachp thank you for reaching out and for the the feedback!  :)

You can use getContent() in order to retrieve a single record using the Record ID. 
You just have to specify the 'recId' after the table name (tableName/recId). 
This will return a single record, you won't need to loop through the records to retrieve the content.

Here's an example:

```
$request = $airtable->getContent( 'Tracks/recsJX1bry74HaGBh' );
$response = $request->getResponse();
echo $response->id;
```

I just did a simple benchmark test for each way. Using a table with less than 500 records, the results were very similar between the two. With a larger set of records, it was much faster to use the Record ID to retrieve your single record. 

I hope this helps!

**Comment by peachp** [comment]
Hi. Thanks for the tip! Yes, it does help even if it won't be much faster, it is still cleaner compared to doing something like:

```
$params = array(
                "filterByFormula" => "AND( RECORD_ID() = '$rec_id' )",
                "maxRecords" => 1,
                "pageSize" => 1
);
```

Thanks again and keep up the good work!

Btw, one of the projects I use your code in is a bespoke theme for the Grav CMS, which will allow to use Airtable as backend / DB for the website. Static pages like Homepage or Contact will be still created in Grav, but repeating, semi-dynamic content such as let's say Portfolio will be managed in Airtable, because it is more comfortable, and in our case we also use the same data for backend order processing. Of course it cannot replace a proper MySQL or similar, but for websites which don't have a lot of visitors and the content doesn't change that often, it's a good GUI / DB combination.
