### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by ravimakwana-wpdeveloper** [sleiman/airtable-php#39]
include('../src/Airtable.php');
include('../src/Request.php');
include('../src/Response.php');

use \TANIOS\Airtable\Airtable;
$airtable = new Airtable(array(
    'api_key' => '*****************',
    'base'    => '******************'
));

$request = $airtable->getContent( 'User' );
do {
    $response = $request->getResponse();
    var_dump( $response[ 'records' ] );
}
while( $request = $response->next() );

print_r($request);

and getting content then got an **error**.

Fatal error: Uncaught Error: Class 'Stiphle\Throttle\LeakyBucket' not found in /var/www/html/myairtableproject/airtable-php-master/src/Airtable.php:46 Stack trace: #0 /var/www/html/myairtableproject/demo.php(28): TANIOS\Airtable\Airtable->__construct(Array) #1 {main} thrown in /var/www/html/myairtableproject/airtable-php-master/src/Airtable.php on line 46

**Comment by sleiman** [comment]
@ravimakwana-wpdeveloper thanks for your message, let me test your code and get back to you in a few minutes.

**Comment by sleiman** [comment]
@ravimakwana-wpdeveloper are you able to use Composer to install the wrapper? We recently updated to add a throttler which would be installed if installed using Composer. The error you are seeing is caused by the missing dependance. We will handle the error in the next version but for now if you used Composer it would work or you can also comment out everything related to Throttle in Airtable.php and Request.php. 

Let me know if that works for you or if you need more help.

**Comment by ravimakwana-wpdeveloper** [comment]
it's getting without install Composer step, just follows the include 3
files. I think your library we can use with composer install and
without composer install use direct include files and use the library.  so
we getting the error in without the composer. with the composer its fine
for us. one more thing in error handling if we not getting proper data from
API then how the response we can set as an error display?.


Thank You
Ravi Makwana B.E.(I.T.)
Mobile No. 9714944808

**Comment by glaliberte** [comment]
@ravimakwana-wpdeveloper Hi, in order to use without composer, you will need to install the dependencies manually and include them with the wrapper at the top of your code.

The dependency that is missing for you is:

**davedevelopment/stiphle**

You need to include it in your code since it's a dependency of the wrapper.

Hope this helps

**Comment by lotharmattt** [comment]
@sleiman @glaliberte Hi guys. Excellent code! Have you had a chance to fix this issue? We also have the same issue (using include, not composer) and had to find and use an older version of yours 2.3.0 with no Throttle stuff. 

Thanks again for the good job!
